name: Scrape OpenSea collection data  

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Extract version from package.json
      uses: sergeysova/jq-action@v2
      id: version
      with:
        cmd: 'jq .version package.json -r'
    - name: Fetch OpenSea data and Push to Repo
      run: |-
        curl https://api.opensea.io/api/v1/collection/doodles-official/stats | jq . > opensea_$(date +"%y%m%d%H").json
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
